POST http://localhost:9000/translate2/en-US
Content-Type: application/json

{
    "text":"天苍苍野茫茫,风吹草低见牛羊",
    "srcLang": "zh"
}

######
POST http://localhost:9000/translate2/en-US
Content-Type: application/json

{
    "text":"一骑红尘妃子笑,无人知是荔枝来",
    "srcLang": "zh"
}

######
POST http://localhost:9000/translate2/id
Content-Type: application/json

{
    "text":"hello world",
    "srcLang": "en"
}




######
POST https://translate.mulai.pw/translate2/en-US
Content-Type: application/json

{
    "text":"对酒当歌人生几何",
    "srcLang": "zh"
}


######
POST https://translate.mulai.pw/translate2/en-US
Content-Type: application/json

{
    "text":"人生得意须尽欢, 莫使金樽空对月",
    "srcLang": "zh"
}


######
POST https://translate.mulai.pw/translate2/en-US
Content-Type: application/json

{
    "text":"落霞与孤鹭齐飞, 秋水共长天一色",
    "srcLang": "zh"
}


######
POST https://translate.mulai.pw/translate2/da-DK
Content-Type: application/json

{
    "text":"You lie",
    "srcLang": "en"
}