POST http://localhost:9000/translate2/en-US
Content-Type: application/json

{
    "text":"天苍苍野茫茫,风吹草低见牛羊",
    "srcLang": "zh"
}


######
POST https://translate.mulai.pw/translate2/en-US
Content-Type: application/json

{
    "text":"对酒当歌人生几何",
    "srcLang": "zh"
}


######
POST https://translate.mulai.pw/translate2/en-US
Content-Type: application/json

{
    "text":"人生得意须尽欢,莫使金樽空对月",
    "srcLang": "zh"
}